lib/dash_web/router.ex
defmodule DashWeb.Router do
  use DashWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug DashWeb.Auth
  end

  # pipeline :api do
  #   plug :accepts, ["json"]
  # end

  scope "/", DashWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/new", PageController, :new
    resources "/users", UserController, except: [:show, :index]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/settings", SettingsController, only: [:edit, :update]
  end

  # Other scopes may use custom stacks.
  # scope "/api", DashWeb do
  #   pipe_through :api
  # end
end

lib/dash/accounts/user.ex
defmodule Dash.Accounts.User do
  use TypedEctoSchema
  @moduledoc "Site user"
  alias Dash.Accounts.Settings
  import Ecto.Changeset

  typed_schema "users" do
    field :email, :string
    field :name, :string
    field :password, :string, virtual: true
    field :password_confirmation, :string, virtual: true
    field :password_hash, :string
    has_one :settings, Settings, on_delete: :delete_all

    timestamps()
  end

  @doc false
  @spec changeset(t(), map) :: Ecto.Changeset.t()
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:email, :name, :password, :password_confirmation])
    |> validate_required([:email, :name, :password, :password_confirmation])
    |> validate_confirmation(:password)
    |> unique_constraint(:email)
    |> put_pass_hash()
  end

  defp put_pass_hash(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{password: pass}} ->
        put_change(changeset, :password_hash, Pbkdf2.hash_pwd_salt(pass))

      _ ->
        changeset
    end
  end
end

lib/dash/github/user.ex
defmodule Dash.Github.User do
  use TypedEctoSchema
  @moduledoc "Site user"
  alias Dash.Github.Settings

  typed_schema "users" do
    has_one :settings, Settings, on_delete: :delete_all

    timestamps()
  end
end

lib/dash/harvest/user.ex
defmodule Dash.Harvest.User do
  use TypedEctoSchema
  @moduledoc "Site user"
  alias Dash.Harvest.Settings

  typed_schema "users" do
    has_one :settings, Settings, on_delete: :delete_all

    timestamps()
  end
end

lib/dash_web/controllers/user_controller.ex
defmodule DashWeb.UserController do
  use DashWeb, :controller

  alias Dash.{Accounts, Backgrounds}
  alias Dash.Accounts.{Policy, User}
  alias DashWeb.Auth

  plug :authenticate when action in [:index, :edit, :update, :delete]

  @spec new(Plug.Conn.t(), map) :: Plug.Conn.t()
  def new(conn, _params) do
    user = Accounts.get_current_user(conn)

    with :ok <- permit(Policy, :new, %User{}, user) do
      changeset = Accounts.change_user(%User{})
      render(conn, "new.html", changeset: changeset)
    end
  end

  @spec create(Plug.Conn.t(), map) :: Plug.Conn.t()
  def create(conn, %{"user" => user_params}) do
    user = Accounts.get_current_user(conn)

    with :ok <- permit(Policy, :create, %User{}, user) do
      case Accounts.create_user(user_params) do
        {:ok, %{user: user}} ->
          conn
          |> Auth.login(user)
          |> put_flash(:info, "User created successfully.")
          |> redirect(to: Routes.user_path(conn, :edit, user))

        {:error, :user, %Ecto.Changeset{} = changeset, %{}} ->
          render(conn, "new.html", changeset: changeset)
      end
    end
  end

  @spec edit(Plug.Conn.t(), map) :: Plug.Conn.t()
  def edit(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    current_user = Accounts.get_current_user(conn)

    with :ok <- permit(Policy, :edit, user, current_user) do
      background = Backgrounds.get(current_user)
      changeset = Accounts.change_user(user)
      render(conn, "edit.html", user: user, changeset: changeset, background: background)
    end
  end

  @spec update(Plug.Conn.t(), map) :: Plug.Conn.t()
  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Accounts.get_user!(id)
    current_user = Accounts.get_current_user(conn)

    with :ok <- permit(Policy, :update, user, current_user) do
      case Accounts.update_user(user, user_params) do
        {:ok, user} ->
          conn
          |> put_flash(:info, "User updated successfully.")
          |> redirect(to: Routes.user_path(conn, :edit, user))

        {:error, %Ecto.Changeset{} = changeset} ->
          render(conn, "edit.html", user: user, changeset: changeset)
      end
    end
  end

  @spec delete(Plug.Conn.t(), map) :: {:error, any} | Plug.Conn.t()
  def delete(conn, %{"id" => id}) do
    current_user = Accounts.get_current_user(conn)
    user = Accounts.get_user!(id)

    with :ok <- permit(Policy, :delete, user, current_user) do
      {:ok, _user} = Accounts.delete_user(user)

      conn
      |> put_flash(:info, "Account deleted successfully.")
      |> redirect(to: Routes.page_path(conn, :index))
    end
  end

  defp authenticate(conn, _opts) do
    if conn.assigns.current_user do
      conn
    else
      conn
      |> put_flash(:error, "You must be logged in to access that page")
      |> redirect(to: Routes.session_path(conn, :new))
      |> halt()
    end
  end

  @spec handle_unauthorized(Plug.Conn.t()) :: Plug.Conn.t()
  def handle_unauthorized(conn) do
    conn
    |> put_flash(:warning, "You are not authorized to access this page")
    |> redirect(to: Routes.page_path(conn, :index))
    |> halt()
  end
end

lib/dash_web/views/user_view.ex
defmodule DashWeb.UserView do
  use DashWeb, :view
end

lib/dash_web/templates/user/edit.html.eex
<div class="box">
  <div class="tabs">
    <ul>
      <li class="is-active"><%= link "User", to: Routes.user_path(@conn, :edit, @user) %></li>
      <li><%= link "API", to: Routes.settings_path(@conn, :edit, @user.settings) %></li>
    </ul>
  </div>

  <h1>User Settings</h1>
  <div class="columns is-centered">
    <div class="column is-narrow">
      <%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update, @user)) %>
    </div>
  </div>
</div>

lib/dash_web/templates/user/form.html.eex
<%= form_for @changeset, @action, [], fn f -> %>
  <%= if @changeset.action do %>
    <div class="notification is-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>
  <div class="field">
  <%= label f, :email, class: "label" %>
  <%= text_input f, :email, class: "input" %>
  <%= error_tag f, :email %>
  </div>

<div class="field">
  <%= label f, :name, class: "label" %>
  <%= text_input f, :name, class: "input" %>
  <%= error_tag f, :name %>
</div>

<div class="field">
  <%= label f, :password, class: "label" %>
  <%= password_input f, :password, class: "input" %>
  <%= error_tag f, :password %>
</div>

<div class="field">
  <%= label f, :password_confirmation, class: "label" %>
  <%= password_input f, :password_confirmation, class: "input" %>
  <%= error_tag f, :password_confirmation %>
</div>

  <div>
    <%= submit "Save", class: "button is-outlined is-primary" %>
  </div>
<% end %>

lib/dash_web/templates/user/index.html.eex
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.name %></td>
      <td>
        <%= link "Edit", to: Routes.user_path(@conn, :edit, user) %>
        <%= link "Delete", to: Routes.user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: Routes.user_path(@conn, :new) %></span>

lib/dash_web/templates/user/new.html.eex
<div class="columns">
  <div class="column"></div>
  <div class="column is-4">
    <h1>Sign Up</h1>
    <%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>
  </div>
  <div class="column"></div>
</div>