lib/dash_web/router.ex
defmodule DashWeb.Router do
  use DashWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug DashWeb.Auth
  end

  # pipeline :api do
  #   plug :accepts, ["json"]
  # end

  scope "/", DashWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/new", PageController, :new
    resources "/users", UserController, except: [:show, :index]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/settings", SettingsController, only: [:edit, :update]
  end

  # Other scopes may use custom stacks.
  # scope "/api", DashWeb do
  #   pipe_through :api
  # end
end

lib/layout_view.ex
defmodule DashWeb.LayoutView do
  use DashWeb, :view
end

lib/dash_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en" class="background">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Dash</title>
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
    integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  <%= csrf_meta_tag() %>
  <%= if assigns[:background] do %>
  <style>
    .background {
      background-image: url(<%= @background.url %>);
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;

      /* Set rules to fill background */
      min-height: 100%;

      /* Set up proportionate scaling */
      width: 100%;
      height: auto;
    }
  </style>
  <% end %>
</head>

<body class="">
  <%= render "navbar.html", conn: @conn, current_user: @current_user %>
  <div class="section">
    <div class="container">
      <%= if info = get_flash(@conn, :info) do %>
      <div class="notification is-info" role="alert"><%= info %></div>
      <% end %>
      <%= if error = get_flash(@conn, :error) do %>
      <div class="notification is-danger" role="alert"><%= error %></div>
      <% end %>
      <%= render @view_module, @view_template, assigns %>
    </div>
  </div>
  <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
</body>

</html>

lib/dash_web/templates/layout/navbar.html.eex
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link "Dash", to: Routes.page_path(@conn, :index), class: 'navbar-item has-text-weight-bold' %>
    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navMenu">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navMenu" class="navbar-menu">
    <div class="navbar-start">
      <%# <a class="navbar-item">
        Home
      </a> %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <%= if @current_user do %>
          <%= link "New background", to: Routes.page_path(@conn, :new), class: "button is-secondary" %>
          <%= link @current_user.name, to: Routes.user_path(@conn, :edit, @current_user), class: "button is-secondary" %>
          <%= link "Log out", to: Routes.session_path(@conn, :delete, @current_user), method: :delete, class: "button is-primary" %>
          <% else %>
          <%= link to: Routes.user_path(@conn, :new), class: "button is-primary" do %>
          <strong>Sign up</strong>
          <% end %>
          <%= link "Log in", to: Routes.session_path(@conn, :new), class: "button is-light" %>
          <% end %>
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>